
sources:
  - type: 'gitlab'
    committerUsername: usernameOnGitlab
    token: glpat-personalaccesstoken
    filters:
      - on: '$project.path_with_namespace'
        regex: '(namespace|anotherone)'
  - type: 'github'
    committerUsername: usernameOnGithub
    # optional, needed to see commits made in private repositories
    token: personalaccesstoken
    filters:
      - on: 'repository.full_name'
        regex: '(namespace|anotherone)'
