name: Bug Report
description: Report an issue that should be fixed
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report.
        Please try to include as much information as possible.
  - type: input
    attributes:
      label: What version of bananareporter is running?
      description: Copy the output of `bananareporter --version`
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a configuration file (with sensitive information redacted) and the CLI command that you are using.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible, please provide text instead of a screenshot.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible, please provide text instead of a screenshot.
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
